#!/usr/bin/env bash
# A script that transfers a file from our client to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to varables

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Disable strict host key check

sco -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if file transfer was successful

if [ $? -eq 0 ]
then
	echo "FILE TRANSFER WAS SUCCESSFUL"
else
	echo "FILE TRANSFER FAILED"
fi
